scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'django-backend'
    static_configs:
      - targets: ['django-backend:8000']  # Update with your backend service name/port

  - job_name: 'intent-nexus-frontend'
    static_configs:
      - targets: ['intent-nexus-frontend:80']  # Update as needed

  - job_name: 'librenms'
    static_configs:
      - targets: ['librenms:8668']

  # Example SNMP scrape for network devices (requires snmp_exporter)
  - job_name: 'network-devices'
    static_configs:
      - targets: ['router1:161', 'switch1:161']
    metrics_path: /snmp
    params:
      module: [if_mib]
