

services:
  syslog-ng:
    build:
      context: ./syslog-ng
    image: balabit/syslog-ng:4.6.0
    container_name: syslog-ng
    ports:
      - "514:514/udp"
      - "601:601/tcp"
    volumes:
      - ./config:/etc/syslog-ng:ro        # config folder is read-only
      - ./logs:/var/log/network           # use host directory for logs
    restart: unless-stopped
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "pgrep", "syslog-ng"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
    env_file:
      - .env

volumes:

networks:
  monitoring:
