version: '3.8'

services:
  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml:ro
      - ./loki/data:/loki
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    depends_on:
      - loki
    volumes:
      - ./promtail/promtail-config.yaml:/etc/promtail/promtail.yaml:ro
      - ./logs:/var/log/syslog-ng:ro
    command: -config.file=/etc/promtail/promtail.yaml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.0.3
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

  syslog-ng:
    image: lscr.io/linuxserver/syslog-ng:latest
    container_name: syslog-ng
    ports:
      - "514:514/udp"
      - "601:601/tcp"
    volumes:
      - ./syslog-ng/config/syslog-ng.conf:/config/syslog-ng.conf:ro
      - ./logs:/var/log/syslog-ng
    restart: unless-stopped

networks:
  default:
    driver: bridge
